# LambdaControls configuration.

# The controls mode. Available modes: default, controller, touchscreen
controls = "default"
# Auto switch mode.
auto_switch_mode = false
# Debug mode
debug = false

[hud]
    # Enables the HUD.
    enable = true
    # Dertermines where the movements buttons are.
    side = "left"

# Gameplay settings
[gameplay]
    # Enables fast block placing like in Bedrock Edition.
    fast_block_placing = true
    # Enables analogic movement if possible.
    analog_movement = true
    # Fly behaviors
    [gameplay.fly]
        # Enables fly drifting.
        drifting = false
        # Enables vertical fly drifting.
        vertical_drifting = true
    [gameplay.reacharound]
        # Enables front block placing like in Bedrock Edition.
        horizontal = false
        # Enables vertical reacharound.
        vertical = false
        # Enables front block placing outline.
        outline = true
        # The color in a hexadecimal format of the outline.
        outline_color = "#ffffff66"

# Controller settings
[controller]
    # Controller to use.
    id = 0
    # Second controller to use.
    id2 = -1
    # Controller's type.
    type = "default"
    # Controller's dead zone.
    dead_zone = 0.20
    # Rotation speed for look directions.
    rotation_speed = 10.0
    # Mouse speed in GUI.
    mouse_speed = 30.0
    # Inverts the right X axis.
    invert_right_x_axis = false
    # Inverts the right Y axis.
    invert_right_y_axis = false
    # Allow unfocused input.
    unfocused_input = false
    # Virtual mouse.
    virtual_mouse = false
    # Virtual mouse skin
    virtual_mouse_skin = "default_light"
    # Controller controls.
    [controller.controls]
        # Attack control.
        attack = "105"
        # Back control.
        back = "201"
        # Open chat control.
        chat = "12"
        # Drop item control.
        drop_item = "1"
        # Forward control.
        forward = "101"
        # Hot-bar left control.
        hotbar_left = "4"
        # Hot-bar right control.
        hotbar_right = "5"
        # Inventory control.
        inventory = "3"
        # Jump control.
        jump = "0"
        # Left movement control.
        left = "200"
        # Pause game control.
        pause_game = "7"
        # Pick block control.
        pick_block = "14"
        # Show player list control.
        player_list = "6"
        # Right movement control.
        right = "100"
        # Take screenshot control.
        screenshot = "11+0"
        # Down slot control.
        slot_down = "13"
        # Left slot control.
        slot_left = "14"
        # Right slot control.
        slot_right = "12"
        # Up slot control.
        slot_up = "11"
        # Sneak control.
        sneak = "10"
        # Sprint control.
        sprint = "9"
        # Swap hands control.
        swap_hands = "2"
        # Switch to back tab control.
        tab_back = "4"
        # Switch to next tab control.
        tab_next = "5"
        # Toggle perspective control.
        toggle_perspective = "11+3"
        # Toggle smooth camera control.
        toggle_smooth_camera = "-1"
        # Use control.
        use = "104"
        # Zoom control.
        zoom = "11+2"
