# LambdaControls configuration.

# The controls mode. Available modes: default, controller, touchscreen
controls = "default"
# Auto switch mode.
auto_switch_mode = false

[hud]
    # Enables the HUD.
    enable = true
    # Dertermines where the movements buttons are.
    side = "left"

# Gameplay settings
[gameplay]
    front_block_placing = false

# Controller settings
[controller]
    # Controller to use.
    id = 0
    # Second controller to use.
    id2 = -1
    # Controller's type.
    type = "default"
    # Controller's dead zone.
    dead_zone = 0.20
    # Rotation speed for look directions.
    rotation_speed = 40.0
    # Mouse speed in GUI.
    mouse_speed = 30.0
    # Inverts the right X axis.
    invert_right_x_axis = false
    # Inverts the right Y axis.
    invert_right_y_axis = false
    # Controller controls.
    [controller.controls]
        # Attack control.
        attack = "105"
        # Back control.
        back = "201"
        # Open chat control.
        chat = "12"
        # Drop item control.
        drop_item = "1"
        # Forward control.
        forward = "101"
        # Hot-bar left control.
        hotbar_left = "4"
        # Hot-bar right control.
        hotbar_right = "5"
        # Inventory control.
        inventory = "3"
        # Jump control.
        jump = "0"
        # Pause game control.
        pause_game = "7"
        # Pick block control.
        pick_block = "14"
        # Show player list control.
        player_list = "6"
        # Take screenshot control.
        screenshot = "11+0"
        # Sneak control.
        sneak = "10"
        # Sprint control.
        sprint = "9"
        # Swap hands control.
        swap_hands = "2"
        # Toggle perspective control.
        toggle_perspective = "11+3"
        # Toggle smooth camera control.
        toggle_smooth_camera = "-1"
        # Use control.
        use = "104"
        # Zoom control.
        zoom = "11+2"
